name: amladpm

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.6
  - numpy=1.14.5
  - pytz=2018.5
  - seaborn
  
  - pip:
    - pyculiarity
    - pytictoc
    - azureml-sdk[automl,notebooks]
    