name: amladpm

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.6
  - numpy=1.14.5
  - pytz=2018.5
  - seaborn
  - jupyter_contrib_nbextensions # jupyter notebook extensions
  - jupyter_nbextensions_configurator # GUI tab for managing extensions
  
  - pip:
    - pyculiarity
    - pytictoc
    - azureml-sdk[automl,notebooks]==0.1.74
    